variables:
- name: SolutionBaseName
  value: sb.DevOps

resources:
  repositories:
  - repository: self
  - repository: sb-devops
    type: github
    name: olusola-adio-sweaty/sb-devops
    endpoint: 'olusola-adio-sweaty'
    ref: refs/tags/v1.11.2

pool:
  name: 'DevOpsPool'
# trigger:
#   branches:
#     include:
#     - master
#     - dev

pr:
  branches:
    include:
    - master
    - dev


stages:
- template: StageTemplates/RunTests.yml
  parameters:
    AzureSubscription: 'sb(318061ea-2105-42da-82d9-b65e8e31017f)'
    Powershell5CodeCoveragePercentage: 37
    PowershellCoreCodeCoveragePercentage: 30


